pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME'
    }

    stages {
        stage('Build Project') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Reporting Test') {
            steps {
                sh 'echo GENERATE REPORT...'
            }
            post {
                always {
                    allure includeProperties: false, results: [[path: 'allure-results']]
                }
            }
        }
    }
}