pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
    }

    stages {
        stage('Build Project') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Run Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh 'mvn test'
                }
            }
        }
        stage('Reporting Test') {
            steps {
                sh 'echo GENERATE REPORT...'
            }
            post {
                always {
                    allure includeProperties: false, results: [[path: 'allure-results']]
                }
            }
        }
    }

    post {
        always {
            script {
                // Verificando o status do build após a execução dos testes
                if (currentBuild.result == 'FAILURE' || currentBuild.result == 'UNSTABLE') {
                    currentBuild.result = 'UNSTABLE' // Garantindo que se houver erro ele seja marcado como UNSTABLE
                } else {
                    currentBuild.result = 'SUCCESS' // Garantindo que se tudo estiver certo, o build será SUCCESS
                }
            }
        }
    }
}